# Generated by Django 5.0 on 2023-12-21 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 21, 3, 20, 41, 317366)),
        ),
    ]
