# Generated by Django 5.0 on 2023-12-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_borrowers_alter_book_date_added_and_more'),
        ('users', '0004_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
