# Generated by Django 5.0 on 2023-12-19 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('available_copies', models.IntegerField()),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 20, 0, 6, 42, 341285))),
                ('img_url', models.CharField()),
            ],
        ),
    ]
