# Generated by Django 5.0 on 2023-12-21 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_date_added_borrow'),
        ('users', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowers',
            field=models.ManyToManyField(through='books.Borrow', to='users.user'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 21, 3, 20, 41, 318367)),
        ),
    ]
